In [ ]:
import cv2
pm=cv2.imread("irony.jpg")#access photo
cv2.imshow("marvel",pm)
cv2.waitKey()
cv2.destroyAllwindows()

In [1]:
import cv2
pm=cv2.imread("irony.jpg")
pm.shape

(1080, 1920, 3)

In [30]:
import cv2
pm=cv2.imread("irony.jpg")#SWAP PHOTO
cm=cv2.imread("SRGI.jpg")
cm[10:200,20:200]
pm[10:200,20:200]=cm[10:200,20:200]
cv2.imshow("marvel",pm)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
import cv2
pm=cv2.imread("irony.jpg") 
r=pm[300:600,700:1000,]
cv2.imshow("CROP",r)
cv2.waitKey()      #crop photo
cv2.destroyAllWindows()


In [14]:
import cv2
pm=cv2.imread("irony.jpg")
pm[ : , : , 0]=0 #REMOVE BLUE COLOR
cv2.imshow("blue",pm)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
import cv2
ar=cv2.imread("irony.jpg")
ar[300:600,600:900]=[0,234,235] #add color
cv2.imshow("addcolor",ar)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
a

array([[89, 89, 89, 89, 89, 89]])

In [36]:
u=[[1,2,3],[4,5,6],[6,7,8],[5,7,8]]
import numpy as pm
a=pm.array([u])
a+=10
a


array([[[11, 12, 13],
        [14, 15, 16],
        [16, 17, 18],
        [15, 17, 18]]])

In [37]:
import cv2
we=cv2.imread("irony.jpg")
we[ : , : ,0]+=100 #amplification
cv2.imshow("apmlifier",we)
cv2.waitKey()
cv2.destroyAllWindows()

In [39]:
import cv2
we=cv2.imread("irony.jpg")
B,G,R=cv2.split(we)

In [40]:
B

array([[47, 47, 48, ..., 22, 22, 22],
       [48, 48, 49, ..., 24, 23, 23],
       [48, 48, 49, ..., 24, 24, 24],
       ...,
       [21, 21, 21, ..., 27, 30, 32],
       [19, 19, 19, ..., 27, 30, 33],
       [18, 18, 18, ..., 28, 30, 33]], dtype=uint8)

In [41]:
G

array([[40, 41, 44, ..., 18, 18, 18],
       [41, 42, 45, ..., 20, 19, 19],
       [41, 42, 45, ..., 20, 20, 20],
       ...,
       [29, 29, 29, ..., 27, 30, 32],
       [27, 27, 27, ..., 27, 30, 33],
       [26, 26, 26, ..., 28, 30, 33]], dtype=uint8)

In [42]:
R

array([[23, 22, 20, ...,  0,  0,  0],
       [24, 23, 21, ...,  1,  0,  0],
       [22, 23, 21, ...,  1,  1,  1],
       ...,
       [59, 59, 59, ..., 27, 30, 32],
       [57, 57, 57, ..., 27, 30, 33],
       [56, 56, 56, ..., 28, 30, 33]], dtype=uint8)

In [47]:
R.shape

(1080, 1920)

In [58]:
import numpy as pm
zeron=pm.zeros((1080,1920))
new=cv2.merge([B,G,z]) #remove red by new way
cv2.imshow("newway",new)
cv2.waitKey()
cv2.destroyAllWindows()


dtype('float64')

In [53]:
z=zeron.astype("uint8")
z.dtype

dtype('uint8')

In [59]:
R.dtype

dtype('uint8')